In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.random.rand(3,3)
array3=np.zeros((4,4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
np.save('array1.npy',array1)

In [5]:
arr1=np.load('array1.npy')
print(arr1)

[[1 2 3]
 [4 5 6]]


In [7]:
# try:
logo=np.load('image1.npy')

plt.figure(figsize=(8,8))
plt.subplot(121)
plt.imshow(logo)
plt.title("Image 1")
plt.grid(False)

# except FileNotFoundError:
#     print("Numpy logo file not found")

ValueError: This file contains pickled (object) data. If you trust the file you can load it unsafely using the `allow_pickle=` keyword argument or `pickle.load()`.