Numpy Array Operations

In [2]:
import numpy as np

Indexing and Slicing

In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing ",arr[2:7])
print("With Steps: ",arr[1:8:2])
print("Negative Indexing",arr[-3])

Basic Slicing  [3 4 5 6 7]
With Steps:  [2 4 6 8]
Negative Indexing 8


In [12]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element: ",arr_2d[2,1])
print("Entire Row: ",arr_2d[1])
print("Entire column: ",arr_2d[:,1])

Specific Element:  8
Entire Row:  [4 5 6]
Entire column:  [2 5 8]


sorting

In [3]:
unsorted=np.array([3,4,5,2,8,1,5,2,6])
print("Sorted Array: ",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d Array by column: \n",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2d Array by Row: \n",np.sort(arr_2d_unsorted,axis=1))

Sorted Array:  [1 2 2 3 4 5 5 6 8]
Sorted 2d Array by column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2d Array by Row: 
 [[1 3]
 [1 2]
 [2 3]]


Filter

In [6]:
numbers=np.arange(1,11)
print("Array is: ",numbers)
evenNumbers=numbers[numbers%2==0]
print("Even Numbers: ",evenNumbers)


Array is:  [ 1  2  3  4  5  6  7  8  9 10]
Even Numbers:  [ 2  4  6  8 10]


Filter with Mask

In [8]:
mask=numbers>5
print("Numbers greater than 5: ",numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


Fancy Indexing and np.where()

In [10]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print("NP where",numbers[where_result])

[1 3 5]
NP where [ 6  7  8  9 10]


In [15]:
condition_array=np.where(numbers>5,numbers*2,numbers)
print(condition_array)
print(numbers)
# if(numbers>5)
# {
#     numbers*4;
# }
# else
# {
#     numbers
# }

[ 1  2  3  4  5 12 14 16 18 20]
[ 1  2  3  4  5  6  7  8  9 10]


Adding and Removing data

In [17]:
arr1=np.array([1,2,4,3])
arr2=np.array([4,5,6,7])
# combined=arr1+arr2
# print("Combined array: ",combined)
combined=np.concatenate((arr1,arr2))
print("Combined array: ",combined)


Combined array:  [1 2 4 3 4 5 6 7]


Array compatibility

In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6,8])
c=np.array([7,8,9])

print("Compatibility Shapes: ",a.shape==b.shape)

Compatibility Shapes:  False


In [22]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
with_new_row=np.vstack((original,new_row)) #always add row

print("Original Array: \n",original)
print("With new Row Array: \n",with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print("With Nen col Array: \n",with_new_col)


Original Array: 
 [[1 2]
 [3 4]]
With new Row Array: 
 [[1 2]
 [3 4]
 [5 6]]
With Nen col Array: 
 [[1 2 7]
 [3 4 8]]


In [24]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print("Array After deletion",deleted)

Array After deletion [1 2 4 5]
