In [ ]:
pip install numpy

In [2]:
import numpy as np

In [ ]:

arr=np.array([4,6,8])
print(arr)

[4 6 8]


In [4]:
arr=np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [6]:
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [7]:
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [14]:
x = np.empty([3,2], dtype = int)
print(x)

[[9218868437227405311   -4503599627370497]
 [4611686018427387904 4372995238176751616]
 [   4503599627370496                   1]]


In [5]:
np_list=[1,2,3]
print(np_list*2)
np_array=np.array([1,2,3])
print(np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range (1000000)]
print(time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print(time.time()-start)

[1, 2, 3, 1, 2, 3]
[2 4 6]
0.5463755130767822
0.018429040908813477


Creating array form scratch

In [11]:
zeroes=np.zeros((3,4))
print("Zeroes Array: \n",zeroes)

ones=np.ones((2,3))
print("Ones Array: \n",ones)


full=np.full((2,2),7)
print("Full Array: \n",full)

random=np.random.random((3,3))
print("Random Array :\n",random)

sequece=np.arange(0,10,2)
print("Sequence Array: ",sequece)

Zeroes Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[7 7]
 [7 7]]
Random Array :
 [[0.82806617 0.99565303 0.73958031]
 [0.2714949  0.77054431 0.40847237]
 [0.79441338 0.28294903 0.02251681]]
Sequence Array:  [0 2 4 6 8]


Vector Matrix And Array

In [12]:
vector=np.array([1,2,3])
print("Vector: ",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("MAtrix: \n",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor: \n",tensor)

Vector:  [1 2 3]
MAtrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [13]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("Dtype: ",arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Dtype:  int64


Array Reshaping

In [20]:
arr=np.arange(12)
print("Original Array: ",arr)


reshaped=arr.reshape((3,4))
print("Reshaped Array: ",reshaped)


flattened=reshaped.flatten()
print("Flattened Array: ",flattened)

raveled=reshaped.ravel() #returns array instead of copy
print("Raveled Array: ",raveled)

#transpose
transpose=reshaped.T
print("Transpose Array :\n",transpose)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
